version: '3.3'
services:
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
#    healthcheck:
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres_user -d market_data'"]
#      interval: 10s
#      timeout: 3s
#      retries: 3
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
  trading_strategy:
    build: .
    entrypoint: "python -m trading_strategy"
    depends_on:
      - db
#      db:
#        condition: service_healthy
    links:
      - db
